dataset:
  name: wine_quality
  target: ""
  csv_path: ""
  test_size: 0.2
  val_size: 0.1
  random_state: 42
  scale_numeric: true
  quality_threshold: 7
  wine_variant: both

bayes:
  bayes_logreg:
    draws: 1000
    tune: 1000
    chains: 2
    target_accept: 0.9
    thin: 100
  bayes_mlp:
    hidden_sizes: [32]
    prior_scale: 1.0
    svi_steps: 1500
    lr: 0.001
    batch_size: 128
    posterior_samples: 400
    random_seed: 42
  # Ensemble construction knobs
  max_members: 10                 # final ensemble size
  candidate_pool_size: 80         # how many posterior draws to consider before selection
  sample_strategy: "linspace"     # one of: linspace | random | thinning | per_chain
  thinning_step: 100              # used when sample_strategy=thinning (every k-th sample)
  per_chain_candidates: null      # used when sample_strategy=per_chain (candidates per chain)
  random_seed: 42                 # seed for reproducibility (random/per_chain top-up)

output:
  results_dir: "results"
  experiment_name: "baseline_wine"
  save_ensemble_metrics_csv: true
  save_member_metrics_csv: true
